// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class Creds {
    "host": string;
    "port": string;
    "user": string;
    "password": string;
    "passphrase": string;

    /** Creates a new Creds instance. */
    constructor($$source: Partial<Creds> = {}) {
        if (!("host" in $$source)) {
            this["host"] = "";
        }
        if (!("port" in $$source)) {
            this["port"] = "";
        }
        if (!("user" in $$source)) {
            this["user"] = "";
        }
        if (!("password" in $$source)) {
            this["password"] = "";
        }
        if (!("passphrase" in $$source)) {
            this["passphrase"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Creds instance from a string or object.
     */
    static createFrom($$source: any = {}): Creds {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Creds($$parsedSource as Partial<Creds>);
    }
}
