// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as ssh$0 from "../../../golang.org/x/crypto/ssh/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function Connect(creds: $models.Creds): $CancellablePromise<ssh$0.Client | null> {
    return $Call.ByID(3754817736, creds).then(($result: any) => {
        return $$createType1($result);
    });
}

export function TestConnection(creds: $models.Creds): $CancellablePromise<boolean> {
    return $Call.ByID(734208430, creds);
}

// Private type creation functions
const $$createType0 = ssh$0.Client.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
